version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: if [ -e ./gradlew ]; then ./gradlew test;else gradle test;fi
      - run:
          name: Generate codecoverage report
          command: if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
      - run:
          name: Upload report
          command: bash <(curl -s https://codecov.io/bash)
